import { onRequest as legacyOnRequest } from "./_middleware.full.js";
const USER_ID="owner", MAIN_ID="main", OLD_KV="chat:main:v1", MAX=12000, MAX_AVATAR=500*1024;
const DEFAULT_TITLES=new Set(["","新聊天","未命名海岸","主聊天"]);
const dec=new TextDecoder();
const H={"Cache-Control":"private, no-store","X-Content-Type-Options":"nosniff","Referrer-Policy":"no-referrer","Content-Type":"application/json; charset=UTF-8"};
function json(x,s=200,h={}){return new Response(JSON.stringify(x),{status:s,headers:{...H,...h}})}
function err(type,message,status=400){return json({ok:false,error:{type,message}},status)}
function sameSite(req){const o=new URL(req.url).origin;const h=req.headers.get("Origin");if(h)return h===o;const r=req.headers.get("Referer");try{return !!r&&new URL(r).origin===o}catch{return false}}
async function bodyText(req){const rd=req.body?.getReader();if(!rd)return"";const a=[];let n=0;while(true){const {done,value}=await rd.read();if(done)break;n+=value.byteLength;if(n>2*1024*1024){const e=new Error("body_too_large");e.status=413;throw e}a.push(value)}const m=new Uint8Array(n);let p=0;for(const c of a){m.set(c,p);p+=c.byteLength}return dec.decode(m)}
async function bodyJson(req){const t=await bodyText(req);return t.trim()?JSON.parse(t):{}}
const id=(v,p="id")=>String(v||"").replace(/[^\w:.-]/g,"_").slice(0,160)||`${p}_${crypto.randomUUID()}`;
const ms=()=>Date.now(), iso=v=>{const n=Number(v||0);return Number.isFinite(n)&&n>0?new Date(n).toISOString():new Date().toISOString()};
const title=(v,f="新聊天")=>String(v||"").replace(/[\r\n\t]+/g," ").replace(/["“”'。.!！?？]+$/g,"").trim().slice(0,40)||f;
const isDefaultTitle=v=>DEFAULT_TITLES.has(String(v||"").trim());
const clip=(v,n=MAX)=>String(v||"").slice(0,n);
const convId=req=>id(new URL(req.url).searchParams.get("conversation_id")||MAIN_ID,"conversation");
const kvKey=c=>`chat:conversation:${id(c,"conversation")}:v1`;
const dbOk=env=>env?.COAST_CHAT_DB&&typeof env.COAST_CHAT_DB.prepare==="function";
const kvOk=env=>env?.COAST_CHAT_STORE&&typeof env.COAST_CHAT_STORE.get==="function"&&typeof env.COAST_CHAT_STORE.put==="function";
async function run(db,sql,args=[]){return db.prepare(sql).bind(...args).run()}
async function all(db,sql,args=[]){return (await db.prepare(sql).bind(...args).all())?.results||[]}
async function first(db,sql,args=[]){return db.prepare(sql).bind(...args).first()}
async function tryRun(db,sql){try{await db.prepare(sql).run()}catch{}}
async function schema(db){
  await tryRun(db,`CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, created_at INTEGER, updated_at INTEGER)`);
  await tryRun(db,`CREATE TABLE IF NOT EXISTS conversations (id TEXT PRIMARY KEY,user_id TEXT,title TEXT,created_at INTEGER,updated_at INTEGER,deleted_at INTEGER,title_manual INTEGER DEFAULT 0,title_generated_at INTEGER DEFAULT NULL,archived_at INTEGER DEFAULT NULL)`);
  await tryRun(db,`CREATE TABLE IF NOT EXISTS turns (id TEXT PRIMARY KEY,conversation_id TEXT,position INTEGER,active_user_variant_id TEXT,created_at INTEGER,updated_at INTEGER,deleted_at INTEGER)`);
  await tryRun(db,`CREATE TABLE IF NOT EXISTS user_variants (id TEXT PRIMARY KEY,turn_id TEXT,position INTEGER,content TEXT,created_at INTEGER,updated_at INTEGER,deleted_at INTEGER)`);
  await tryRun(db,`CREATE TABLE IF NOT EXISTS assistant_variants (id TEXT PRIMARY KEY,turn_id TEXT,user_variant_id TEXT,user_variant_position INTEGER,position INTEGER,content TEXT,error_detail TEXT,is_active INTEGER DEFAULT 0,created_at INTEGER,updated_at INTEGER,deleted_at INTEGER)`);
  await tryRun(db,`CREATE TABLE IF NOT EXISTS chat_profiles (user_id TEXT PRIMARY KEY,assistant_avatar_dataurl TEXT DEFAULT NULL,current_chat_model TEXT DEFAULT NULL,current_image_model TEXT DEFAULT NULL,model_box_json TEXT DEFAULT NULL,updated_at INTEGER NOT NULL)`);
  for(const s of [`ALTER TABLE conversations ADD COLUMN title_manual INTEGER DEFAULT 0`,`ALTER TABLE conversations ADD COLUMN title_generated_at INTEGER DEFAULT NULL`,`ALTER TABLE conversations ADD COLUMN archived_at INTEGER DEFAULT NULL`])await tryRun(db,s);
  await tryRun(db,`CREATE INDEX IF NOT EXISTS idx_conv_owner ON conversations(user_id,deleted_at,updated_at)`);
  await tryRun(db,`CREATE INDEX IF NOT EXISTS idx_turns_conv ON turns(conversation_id,position)`);
  await tryRun(db,`CREATE INDEX IF NOT EXISTS idx_user_turn ON user_variants(turn_id,position)`);
  await tryRun(db,`CREATE INDEX IF NOT EXISTS idx_asst_turn ON assistant_variants(turn_id,user_variant_position,position)`);
}
async function owner(db){const t=ms();await run(db,`INSERT OR IGNORE INTO users (id,created_at,updated_at) VALUES (?,?,?)`,[USER_ID,t,t]);await run(db,`UPDATE users SET updated_at=? WHERE id=?`,[t,USER_ID])}
async function ensure(db){await schema(db);await owner(db)}
function convRow(r){return{id:r.id,title:r.title||"新聊天",created_at:iso(r.created_at),updated_at:iso(r.updated_at),deleted_at:r.deleted_at?iso(r.deleted_at):null,title_manual:Number(r.title_manual||0)===1,title_generated_at:r.title_generated_at?iso(r.title_generated_at):null}}
function cleanList(v){return Array.isArray(v)?v.filter(x=>typeof x==="string").map(x=>x.slice(0,180)).slice(0,60):[]}
function profile(p={}){const av=clip(p.assistant_avatar_dataurl??p.assistantAvatarDataUrl??"",MAX_AVATAR+1);if(av.length>MAX_AVATAR){const e=new Error("profile_avatar_too_large");e.status=413;throw e}const b=p.model_box||p.modelBox||{};return{assistant_avatar_dataurl:av,current_chat_model:clip(p.current_chat_model??p.currentChatModel??"",180),current_image_model:clip(p.current_image_model??p.currentImageModel??"",180),model_box:b&&typeof b==="object"?{chat:cleanList(b.chat),free:cleanList(b.free),image:cleanList(b.image)}:{chat:[],free:[],image:[]}}}
const emptyProfile=()=>({assistant_avatar_dataurl:"",current_chat_model:"",current_image_model:"",model_box:{chat:[],free:[],image:[]}});
function variant(v,p){if(!v||typeof v.content!=="string")return null;return{id:id(v.id||crypto.randomUUID(),p),content:clip(v.content),created_at:typeof v.created_at==="string"?v.created_at:new Date().toISOString(),...(typeof v.errorDetail==="string"&&v.errorDetail?{errorDetail:clip(v.errorDetail)}:{})}}
function normTurns(turns=[]){return(Array.isArray(turns)?turns:[]).slice(-100).map(t=>{const u=(Array.isArray(t?.user?.variants)?t.user.variants:[]).map(x=>variant(x,"user_variant")).filter(Boolean).slice(0,20);const count=Math.max(1,u.length);const vb={},ab={};for(let i=0;i<count;i++){const k=String(i),l=(Array.isArray(t?.assistant?.variantsByUserVariant?.[k])?t.assistant.variantsByUserVariant[k]:[]).map(x=>variant(x,"assistant_variant")).filter(Boolean).slice(0,20);vb[k]=l;ab[k]=Math.min(Math.max(0,Number(t?.assistant?.activeByUserVariant?.[k]||0)),Math.max(0,l.length-1))}return{id:id(t?.id||crypto.randomUUID(),"turn"),user:{active:Math.min(Math.max(0,Number(t?.user?.active||0)),Math.max(0,u.length-1)),variants:u},assistant:{activeByUserVariant:ab,variantsByUserVariant:vb}}}).filter(t=>t.user.variants.length||Object.values(t.assistant.variantsByUserVariant).some(l=>l.length))}
function flatToTurns(msgs=[]){const out=[];let cur=null;for(const m of (Array.isArray(msgs)?msgs:[]).filter(x=>x&&(x.role==="user"||x.role==="assistant")&&typeof x.content==="string").slice(-200)){const v=variant(m,m.role==="user"?"user_variant":"assistant_variant");if(m.role==="user"){cur={id:id(`turn_${v.id}`,"turn"),user:{active:0,variants:[v]},assistant:{activeByUserVariant:{0:0},variantsByUserVariant:{0:[]}}};out.push(cur)}else if(cur)cur.assistant.variantsByUserVariant[0].push(v)}return normTurns(out)}
function histFromBody(b){const p=profile(b.profile||b.history?.profile||{});const turns=normTurns(b.turns||b.history?.turns||[]);if(turns.length)return{v:2,updated_at:new Date().toISOString(),turns,profile:p};return{v:2,updated_at:new Date().toISOString(),turns:flatToTurns(b.messages||b.history?.messages||[]),profile:p}}
async function readProfile(db){const r=await first(db,`SELECT assistant_avatar_dataurl,current_chat_model,current_image_model,model_box_json FROM chat_profiles WHERE user_id=?`,[USER_ID]);if(!r)return emptyProfile();let box={chat:[],free:[],image:[]};try{box=JSON.parse(r.model_box_json||"{}")}catch{}return profile({assistant_avatar_dataurl:r.assistant_avatar_dataurl||"",current_chat_model:r.current_chat_model||"",current_image_model:r.current_image_model||"",model_box:box})}
async function writeProfile(db,p,t=ms()){const c=profile(p||{});await run(db,`INSERT INTO chat_profiles (user_id,assistant_avatar_dataurl,current_chat_model,current_image_model,model_box_json,updated_at) VALUES (?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET assistant_avatar_dataurl=excluded.assistant_avatar_dataurl,current_chat_model=excluded.current_chat_model,current_image_model=excluded.current_image_model,model_box_json=excluded.model_box_json,updated_at=excluded.updated_at`,[USER_ID,c.assistant_avatar_dataurl||null,c.current_chat_model||null,c.current_image_model||null,JSON.stringify(c.model_box),t]);return c}
async function listConvs(db){await ensure(db);return(await all(db,`SELECT id,title,created_at,updated_at,deleted_at,title_manual,title_generated_at FROM conversations WHERE user_id=? AND deleted_at IS NULL ORDER BY updated_at DESC,created_at DESC`,[USER_ID])).map(convRow)}
async function createConv(db,t="新聊天"){await ensure(db);const n=ms(),cid=id(crypto.randomUUID(),"conversation"),ttl=title(t);await run(db,`INSERT INTO conversations (id,user_id,title,created_at,updated_at,deleted_at,title_manual,title_generated_at) VALUES (?,?,?,?,?,NULL,0,NULL)`,[cid,USER_ID,ttl,n,n]);return{id:cid,title:ttl,created_at:iso(n),updated_at:iso(n),deleted_at:null,title_manual:false,title_generated_at:null}}
async function ensureConv(db,cid,t="新聊天"){await ensure(db);const n=ms();await run(db,`INSERT INTO conversations (id,user_id,title,created_at,updated_at,deleted_at,title_manual,title_generated_at) VALUES (?,?,?,?,?,NULL,0,NULL) ON CONFLICT(id) DO UPDATE SET user_id=excluded.user_id,deleted_at=NULL`,[cid,USER_ID,title(t),n,n])}
async function patchConv(db,cid,t){await ensureConv(db,cid,t);const n=ms(),ttl=title(t);await run(db,`UPDATE conversations SET title=?,title_manual=1,updated_at=? WHERE id=? AND user_id=? AND deleted_at IS NULL`,[ttl,n,cid,USER_ID]);return convRow(await first(db,`SELECT id,title,created_at,updated_at,deleted_at,title_manual,title_generated_at FROM conversations WHERE id=? AND user_id=?`,[cid,USER_ID]))}
async function deleteConv(db,cid){await ensure(db);const n=ms();await run(db,`UPDATE conversations SET deleted_at=?,updated_at=? WHERE id=? AND user_id=?`,[n,n,cid,USER_ID]);return{id:cid,deleted_at:iso(n)}}
async function readHistory(db,cid){await ensure(db);const prof=await readProfile(db);const c=await first(db,`SELECT id,updated_at FROM conversations WHERE id=? AND user_id=? AND deleted_at IS NULL`,[cid,USER_ID]);if(!c)return{v:2,source:"d1",conversation_id:cid,updated_at:null,turns:[],profile:prof};const tr=await all(db,`SELECT id,position,active_user_variant_id,updated_at FROM turns WHERE conversation_id=? AND deleted_at IS NULL ORDER BY position ASC,created_at ASC`,[cid]);if(!tr.length)return{v:2,source:"d1",conversation_id:cid,updated_at:iso(c.updated_at),turns:[],profile:prof};const ids=tr.map(x=>x.id),ph=ids.map(()=>"?").join(",");const ur=await all(db,`SELECT id,turn_id,position,content,created_at FROM user_variants WHERE deleted_at IS NULL AND turn_id IN (${ph}) ORDER BY turn_id ASC,position ASC`,ids);const ar=await all(db,`SELECT id,turn_id,user_variant_id,user_variant_position,position,content,error_detail,is_active,created_at FROM assistant_variants WHERE deleted_at IS NULL AND turn_id IN (${ph}) ORDER BY turn_id ASC,user_variant_position ASC,position ASC`,ids);const uMap=new Map(),uIdx=new Map();for(const r of ur){const l=uMap.get(r.turn_id)||[];l.push({id:r.id,content:r.content||"",created_at:iso(r.created_at)});uMap.set(r.turn_id,l)}for(const [tid,l] of uMap.entries())l.forEach((v,i)=>uIdx.set(`${tid}:${v.id}`,i));const aMap=new Map(),act=new Map();for(const r of ar){const br=r.user_variant_id?uIdx.get(`${r.turn_id}:${r.user_variant_id}`):null;const bi=br==null?Number(r.user_variant_position||0):br;const k=`${r.turn_id}:${bi}`;const l=aMap.get(k)||[];l.push({id:r.id,content:r.content||"",created_at:iso(r.created_at),...(r.error_detail?{errorDetail:r.error_detail}:{})});if(Number(r.is_active||0)===1)act.set(k,Math.max(0,l.length-1));aMap.set(k,l)}const turns=tr.map(r=>{const u=uMap.get(r.id)||[];const ai=u.findIndex(v=>v.id===r.active_user_variant_id);const vb={},ab={};for(let i=0;i<Math.max(1,u.length);i++){const k=`${r.id}:${i}`;vb[String(i)]=aMap.get(k)||[];ab[String(i)]=Math.min(Math.max(0,Number(act.get(k)||0)),Math.max(0,vb[String(i)].length-1))}return{id:r.id,user:{active:ai>=0?ai:0,variants:u},assistant:{activeByUserVariant:ab,variantsByUserVariant:vb}}});return{v:2,source:"d1",conversation_id:cid,updated_at:iso(c.updated_at),turns:normTurns(turns),profile:prof}}
function activeUser(t){const i=Math.min(Math.max(0,Number(t.user.active||0)),Math.max(0,t.user.variants.length-1));return t.user.variants[i]?.id||null}
async function markGone(db,table,col,ids,where,args,n){if(ids.length){await run(db,`UPDATE ${table} SET deleted_at=? ${where} AND ${col} NOT IN (${ids.map(()=>"?").join(",")})`,[n,...args,...ids])}else await run(db,`UPDATE ${table} SET deleted_at=? ${where}`,[n,...args])}
async function writeHistory(db,cid,input){await ensure(db);const n=ms();const h={...input,turns:normTurns(input.turns||[]),conversation_id:cid};h.profile=await writeProfile(db,input.profile||{},n);await run(db,`INSERT INTO conversations (id,user_id,title,created_at,updated_at,deleted_at,title_manual,title_generated_at) VALUES (?,?,?,?,?,NULL,0,NULL) ON CONFLICT(id) DO UPDATE SET user_id=excluded.user_id,updated_at=excluded.updated_at,deleted_at=NULL`,[cid,USER_ID,"新聊天",n,n]);const tids=[],uids=[],aids=[];for(let ti=0;ti<h.turns.length;ti++){const t=h.turns[ti],tid=id(t.id,"turn");tids.push(tid);await run(db,`INSERT INTO turns (id,conversation_id,position,active_user_variant_id,created_at,updated_at,deleted_at) VALUES (?,?,?,?,?,?,NULL) ON CONFLICT(id) DO UPDATE SET conversation_id=excluded.conversation_id,position=excluded.position,active_user_variant_id=excluded.active_user_variant_id,updated_at=excluded.updated_at,deleted_at=NULL`,[tid,cid,ti,activeUser(t),n,n]);for(let ui=0;ui<t.user.variants.length;ui++){const u=t.user.variants[ui],uid=id(u.id,"user_variant");uids.push(uid);await run(db,`INSERT INTO user_variants (id,turn_id,position,content,created_at,updated_at,deleted_at) VALUES (?,?,?,?,?,?,NULL) ON CONFLICT(id) DO UPDATE SET turn_id=excluded.turn_id,position=excluded.position,content=excluded.content,updated_at=excluded.updated_at,deleted_at=NULL`,[uid,tid,ui,u.content,Date.parse(u.created_at||"")||n,n]);const l=t.assistant.variantsByUserVariant[String(ui)]||[],act=C(t.assistant.activeByUserVariant[String(ui)],l.length||1);for(let ai=0;ai<l.length;ai++){const a=l[ai],aid=id(a.id,"assistant_variant");aids.push(aid);await run(db,`INSERT INTO assistant_variants (id,turn_id,user_variant_id,user_variant_position,position,content,error_detail,is_active,created_at,updated_at,deleted_at) VALUES (?,?,?,?,?,?,?,?,?,?,NULL) ON CONFLICT(id) DO UPDATE SET turn_id=excluded.turn_id,user_variant_id=excluded.user_variant_id,user_variant_position=excluded.user_variant_position,position=excluded.position,content=excluded.content,error_detail=excluded.error_detail,is_active=excluded.is_active,updated_at=excluded.updated_at,deleted_at=NULL`,[aid,tid,uid,ui,ai,a.content,a.errorDetail||null,ai===act?1:0,Date.parse(a.created_at||"")||n,n])}}}await markGone(db,"turns","id",tids,"WHERE conversation_id=?",[cid],n);await markGone(db,"user_variants","id",uids,"WHERE turn_id IN (SELECT id FROM turns WHERE conversation_id=?)",[cid],n);await markGone(db,"assistant_variants","id",aids,"WHERE turn_id IN (SELECT id FROM turns WHERE conversation_id=?)",[cid],n);h.updated_at=new Date(n).toISOString();return h}
async function clearHistory(db,cid){await ensureConv(db,cid);const n=ms();await run(db,`UPDATE conversations SET updated_at=? WHERE id=? AND user_id=?`,[n,cid,USER_ID]);await run(db,`UPDATE turns SET deleted_at=?,updated_at=? WHERE conversation_id=?`,[n,n,cid]);await run(db,`UPDATE user_variants SET deleted_at=?,updated_at=? WHERE turn_id IN (SELECT id FROM turns WHERE conversation_id=?)`,[n,n,cid]);await run(db,`UPDATE assistant_variants SET deleted_at=?,updated_at=? WHERE turn_id IN (SELECT id FROM turns WHERE conversation_id=?)`,[n,n,cid])}
function kvNorm(p){const raw=p?.history||p||{};return{v:2,source:p?.source||"kv",updated_at:raw.updated_at||p?.updated_at||null,turns:Array.isArray(raw.turns)?normTurns(raw.turns):flatToTurns(raw.messages||p?.messages||[]),profile:profile(raw.profile||p?.profile||{})}}
async function readKv(env,cid){if(!kvOk(env))return null;for(const k of [kvKey(cid),cid===MAIN_ID?OLD_KV:null].filter(Boolean)){const r=await env.COAST_CHAT_STORE.get(k);if(r)try{return kvNorm(JSON.parse(r))}catch{}}return null}
async function writeKv(env,cid,h){if(!kvOk(env))return;await env.COAST_CHAT_STORE.put(kvKey(cid),JSON.stringify({v:2,source:"d1-cache",updated_at:h.updated_at||new Date().toISOString(),history:{conversation_id:cid,turns:normTurns(h.turns||[]),profile:profile(h.profile||{})}}))}
async function delKv(env,cid){if(kvOk(env)&&typeof env.COAST_CHAT_STORE.delete==="function")await env.COAST_CHAT_STORE.delete(kvKey(cid))}
async function handleHistory(req,env){const cid=convId(req);if(req.method==="GET"){if(dbOk(env))try{let h=await readHistory(env.COAST_CHAT_DB,cid);if(!h.turns.length){const kv=await readKv(env,cid);if(kv?.turns?.length){h=await writeHistory(env.COAST_CHAT_DB,cid,{...kv,profile:{...h.profile,...kv.profile}});await writeKv(env,cid,h);return json({ok:true,source:cid===MAIN_ID?"d1-migrated-from-kv":"d1-migrated-from-conversation-kv",history:h})}}await writeKv(env,cid,h);return json({ok:true,source:"d1",history:h})}catch{const kv=await readKv(env,cid);if(kv)return json({ok:true,source:"kv-fallback",warning:"d1_read_failed",history:{...kv,conversation_id:cid}});return err("chat_db_unavailable","主聊天 D1 存储暂不可用。",503)}const kv=await readKv(env,cid);if(kv)return json({ok:true,source:"kv-fallback",warning:"chat_db_not_configured",history:{...kv,conversation_id:cid}});return err("chat_db_not_configured","主聊天 D1 存储未配置。",503)}if(req.method==="PUT"){if(!sameSite(req))return err("forbidden","Forbidden.",403);if(!dbOk(env))return err("chat_db_not_configured","主聊天 D1 存储未配置。",503);let b;try{b=await bodyJson(req)}catch(e){return err(e.status===413?"body_too_large":"invalid_request",e.status===413?"请求体过大。":"请求体无效。",e.status===413?413:400)}let h;try{h=histFromBody(b)}catch(e){return err("profile_avatar_too_large","头像数据过大，未写入服务器。",413)}try{const saved=await writeHistory(env.COAST_CHAT_DB,cid,h);await writeKv(env,cid,saved);return json({ok:true,source:"d1",history:saved})}catch{return err("chat_db_write_failed","主聊天 D1 写入失败。",500)}}if(req.method==="DELETE"){if(!sameSite(req))return err("forbidden","Forbidden.",403);if(dbOk(env))await clearHistory(env.COAST_CHAT_DB,cid);await delKv(env,cid);return json({ok:true,source:dbOk(env)?"d1":"kv",conversation_id:cid,deleted:true})}return json({ok:false,error:{type:"method_not_allowed",message:"Method not allowed."}},405,{Allow:"GET, PUT, DELETE"})}
async function handleConvs(req,env){if(!dbOk(env))return err("chat_db_not_configured","主聊天 D1 存储未配置。",503);const url=new URL(req.url),prefix="/api/chat/conversations",rest=decodeURIComponent(url.pathname.slice(prefix.length).replace(/^\//,""));if(!rest){if(req.method==="GET")return json({ok:true,conversations:await listConvs(env.COAST_CHAT_DB)});if(req.method==="POST"){if(!sameSite(req))return err("forbidden","Forbidden.",403);const b=await bodyJson(req).catch(()=>({}));return json({ok:true,conversation:await createConv(env.COAST_CHAT_DB,b.title||"新聊天")},201)}return err("method_not_allowed","Method not allowed.",405)}const cid=id(rest.split("/")[0],"conversation");if(req.method==="PATCH"){if(!sameSite(req))return err("forbidden","Forbidden.",403);const b=await bodyJson(req).catch(()=>({}));return json({ok:true,conversation:await patchConv(env.COAST_CHAT_DB,cid,b.title||"新聊天")})}if(req.method==="DELETE"){if(!sameSite(req))return err("forbidden","Forbidden.",403);const c=await deleteConv(env.COAST_CHAT_DB,cid);await delKv(env,cid);return json({ok:true,conversation:c,deleted:true})}return err("method_not_allowed","Method not allowed.",405)}
async function genTitle(context,user,assistant){const u=new URL(context.request.url);u.pathname="/api/chat";u.search="";const prompt=`为下面这轮对话生成一个简短中文标题，12字以内，不要引号，不要句号，不要解释。\n用户：${String(user||"").slice(0,1000)}\n助手：${String(assistant||"").slice(0,1000)}`;const r=new Request(u.toString(),{method:"POST",headers:new Headers({"Content-Type":"application/json",Cookie:context.request.headers.get("Cookie")||""}),body:JSON.stringify({model:"openai/gpt-4.1-nano",messages:[{role:"user",content:prompt}],settings:{max_tokens:40,temperature:.2}})});const res=await legacyOnRequest({...context,request:r});const data=await res.json().catch(()=>({}));if(!res.ok||data.ok===false)throw Error("title_generation_failed");return title(data?.message?.content||"","新聊天").slice(0,24)}
async function handleTitle(req,context){const env=context.env;if(!dbOk(env))return err("chat_db_not_configured","主聊天 D1 存储未配置。",503);if(req.method!=="POST")return err("method_not_allowed","Method not allowed.",405);if(!sameSite(req))return err("forbidden","Forbidden.",403);const b=await bodyJson(req).catch(()=>({})),cid=id(b.conversation_id||MAIN_ID,"conversation");await ensure(env.COAST_CHAT_DB);const r=await first(env.COAST_CHAT_DB,`SELECT id,title,title_manual,title_generated_at,deleted_at FROM conversations WHERE id=? AND user_id=?`,[cid,USER_ID]);if(!r||r.deleted_at)return err("conversation_not_found","会话不存在。",404);if(Number(r.title_manual||0)===1||r.title_generated_at||!isDefaultTitle(r.title))return json({ok:true,skipped:true});let ttl;try{ttl=await genTitle(context,b.user||"",b.assistant||"")}catch{return json({ok:true,skipped:true,reason:"title_generation_failed"})}const n=ms();await run(env.COAST_CHAT_DB,`UPDATE conversations SET title=?,title_generated_at=?,updated_at=? WHERE id=? AND user_id=? AND (title_manual IS NULL OR title_manual!=1) AND deleted_at IS NULL`,[ttl,n,n,cid,USER_ID]);return json({ok:true,conversation:convRow(await first(env.COAST_CHAT_DB,`SELECT id,title,created_at,updated_at,deleted_at,title_manual,title_generated_at FROM conversations WHERE id=? AND user_id=?`,[cid,USER_ID]))})}
async function auth(context){const u=new URL(context.request.url);u.pathname="/api/session";u.search="";const res=await legacyOnRequest({...context,request:new Request(u.toString(),{method:"GET",headers:context.request.headers})});return res.ok?null:res}
export async function onRequest(context){const url=new URL(context.request.url);if(url.pathname==="/api/chat/history"){const a=await auth(context);if(a)return a;return handleHistory(context.request,context.env)}if(url.pathname==="/api/chat/conversations"||url.pathname.startsWith("/api/chat/conversations/")){const a=await auth(context);if(a)return a;return handleConvs(context.request,context.env)}if(url.pathname==="/api/chat/title"){const a=await auth(context);if(a)return a;return handleTitle(context.request,context)}return legacyOnRequest(context)}
